### ISSUE TITLE
kubernetes: missing flag for readiness and liveness probes

### ISSUE THREAD

**Issue by vincentbernaud** [grafana/synthetic-monitoring-agent#393]
Hi, 

When trying to deploy probes in our kubernetes clusters, we used your kubernetes example to create an helm chart and noticed that it is not working as expected. 

The default binding address of the agent is localhost:4050, causing the readiness and liveness requests (sent by kubelet) to fail and creates a CrashLoopBackoff error. 

It can be fixed by adding the `--listen-address="0.0.0.0:4050"` flag to the container args.
```
containers:
  - name: {{ .Chart.Name }}
    args:
      - /usr/local/bin/synthetic-monitoring-agent --api-server-address=${API_SERVER} --api-token=${API_TOKEN} --verbose=true --listen-address="0.0.0.0:4050"
    command:
      - sh
      - -c
...
```

I'll be happy to share the full helm chart if you're interested.
